//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chess.View {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class ChessAppSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static ChessAppSettings defaultInstance = ((ChessAppSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ChessAppSettings())));
        
        public static ChessAppSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChessGameColumnWidth {
            get {
                return ((string)(this["ChessGameColumnWidth"]));
            }
            set {
                this["ChessGameColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ConsoleColumnWidth {
            get {
                return ((string)(this["ConsoleColumnWidth"]));
            }
            set {
                this["ConsoleColumnWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChessMovesListViewRowHeight {
            get {
                return ((string)(this["ChessMovesListViewRowHeight"]));
            }
            set {
                this["ChessMovesListViewRowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChessMovesNotesRowHeight {
            get {
                return ((string)(this["ChessMovesNotesRowHeight"]));
            }
            set {
                this["ChessMovesNotesRowHeight"] = value;
            }
        }
    }
}
