//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chess.Services {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class SerializeSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SerializeSettings defaultInstance = ((SerializeSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SerializeSettings())));
        
        public static SerializeSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BoardSerializedString {
            get {
                return ((string)(this["BoardSerializedString"]));
            }
            set {
                this["BoardSerializedString"] = value;
            }
        }
    }
}
